language: csharp
mono: none
os: linux
dotnet: 3.1.101

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
  - dotnet restore ./MochaDB/MochaDB.csproj
  - dotnet build ./MochaDB/MochaDB.csproj -f netstandard1.3
  - dotnet test ./MochaDB/MochaDB.csproj --logger:console --verbosity=minimal

notifications:
  email: false  

