language: csharp
mono: none
os: linux
dotnet: 3.1.101

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
  # MochaDB
  - dotnet restore ./src/MochaDB.csproj
  - dotnet build ./src/MochaDB.csproj -f netstandard1.3
  - dotnet test ./src/MochaDB.csproj --logger:console --verbosity=minimal
  # fsharptest
  - dotnet restore ./fsharptest/fsharptest.fsproj
  - dotnet build ./fsharptest/fsharptest.fsproj
  - dotnet test ./fsharptest/fsharptest.fsproj

notifications:
  email: false  

