language: csharp
mono: none
os: linux
dotnet: 3.1.101

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
  - dotnet restore ./src/MochaDB.csproj
  - dotnet build ./src/MochaDB.csproj -f netstandard2.1
  - dotnet test ./src/MochaDB.csproj --logger:console --verbosity=minimal

notifications:
  email: false  

